version: '3'
services:

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=test
      - PGHOST=postgres
      - PGDATABASE=postgres
